name: 'Bisection JuliaLang/PackageCompiler.jl#445'

on:
  push:
  workflow_dispatch:

jobs:
  search:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        revision:
          - 8659cfeda7afa5cf665e282e927812f0a9d51d03
          - 03ec50d7dd997be827d1b82c90b19f4be780c792
          - b18647edda608d473b049ef2c7a40a9d481f0e2d
          - c718376d3adeadfba101cb2255dabfa3dffa45b2
          - 26e38cc6f96ff3d32cc67e1426d8b69213ce497d
          - 5f55b977e439ab7b0d09dd826732ff5ea3f1098f
          - 5a86131b14d2a8967141c7eadd3095f1b84a64e1
          - 10e2455860888f1a2a0b34adc1c0f352181343b1
          - 9ffc7036ff420ca6fe3be61c4540cca5b235deb4
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2000
      - uses: actions/cache@v2
        env:
          cache-name: cache-srccache
        with:
          path: deps/srccache
          key: ${{ env.cache-name }}

      - run: cp test.sh /tmp/test.sh
      - run: git checkout ${{ matrix.revision }}
      - run: /tmp/test.sh
