name: 'Bisection JuliaLang/PackageCompiler.jl#445'

on:
  push:
  workflow_dispatch:

jobs:
  bisect:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2000
      - uses: actions/cache@v2
        env:
          cache-name: cache-srccache
        with:
          path: deps/srccache
          key: ${{ env.cache-name }}
      - run: make -j2
      - run: ./julia -e 'using Pkg; pkg"add PackageCompiler#cb994c72e2087c57ffa4727ef93589e1b98d8a32"'
      - run: ./julia -e 'using Pkg; pkg"dev PyCall"'
      - run: cp test.sh /tmp/test.sh

      - run: git checkout 9ffc7036ff420ca6fe3be61c4540cca5b235deb4
      - run: "! /tmp/test.sh"

      - run: git checkout 8659cfeda7afa5cf665e282e927812f0a9d51d03
      - run: /tmp/test.sh

      - run: git bisect start
      - run: git bisect good 8659cfeda7afa5cf665e282e927812f0a9d51d03
      - run: git bisect bad 9ffc7036ff420ca6fe3be61c4540cca5b235deb4
      - run: git bisect run /tmp/test.sh
