name: 'Bisection JuliaLang/PackageCompiler.jl#445'

on:
  push:
  workflow_dispatch:

jobs:
  bisect:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2000
      - uses: actions/cache@v2
        env:
          cache-name: cache-srccache
        with:
          path: deps/srccache
          key: ${{ env.cache-name }}
      - run: make -j2
