name: 'Bisection JuliaLang/PackageCompiler.jl#445'

on:
  push:
  workflow_dispatch:

jobs:
  search:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        revision:
          - 9738c14bdfab5aa1c0c51f8928157068f214cb6b
          - fafc0a4ee38d401aab2ac2027cc2b75c1d296faa
          - 7bab22eda6f4a274a70001f5b292e71add572558
          - e37876793f77b516c30000b66b373e71b1e462e5
          - 4a6d7bfcad3fdcb9ba7773f797502db80e457f56
          - 54ed72a45c9b8b6bc6fa001755fa4d15ccd61c5f
          - 83d0beca4118cec532a4d7c753ec360f160e3822
          - 54946b01bd04b24f72c862190e8d2eab7845ec68
          - bc870caf331a8de9352afe525e0c6977bf96c7f8
          - c4226dddbc73881ba51710e1166e03c2ea70fa63
          - 5d79f76b320db10ef34026280db2afe10fc9bf4b
          - ace08d84d69d4bd807bb4bc26a18c8a3494afe6b
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2000
      - uses: actions/cache@v2
        env:
          cache-name: cache-srccache
        with:
          path: deps/srccache
          key: ${{ env.cache-name }}

      - run: cp test.sh /tmp/test.sh
      - run: git checkout ${{ matrix.revision }}
      - run: /tmp/test.sh
