name: Find a bug

on:
  push:
  workflow_dispatch:

jobs:
  search:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        revision:
          - 2479691a5a91051d0b71552ecbcf6724a45409a7
          - 4e07a3993a07d77be05bab55272e9f2cae26d723
          - 4e07a3993a07d77be05bab55272e9f2cae26d723
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2000
      - uses: actions/cache@v2
        env:
          cache-name: cache-srccache
        with:
          path: deps/srccache
          key: ${{ env.cache-name }}

      - run: cp test.sh /tmp/test.sh
      - run: cp -r Repro /tmp/
      - run: git checkout ${{ matrix.revision }}
      - run: /tmp/test.sh
