name: Find a bug

on:
  push:
  workflow_dispatch:

jobs:
  search:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2000

      - run: cp test.sh /tmp/test.sh
      - run: cp -r Repro /tmp/

      - run: git bisect start
      - run: git bisect bad bc870caf331a8de9352afe525e0c6977bf96c7f8
      - run: git bisect good 4ef8313c94c85b3e01597455cb71a60a579f632b
      - run: git bisect run /tmp/test.sh
