name: Find a bug

on:
  push:
  workflow_dispatch:

jobs:
  search:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2000

      - run: cp test.sh /tmp/test.sh
      - run: cp -r Repro /tmp/

      - run: git bisect start
      - run: git bisect bad 2479691a5a91051d0b71552ecbcf6724a45409a7
      - run: git bisect good 4e07a3993a07d77be05bab55272e9f2cae26d723
      - run: git bisect run /tmp/test.sh
