name: Find bug

on:
  push:
  workflow_dispatch:

jobs:
  search:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        revision:
          - d9bf55c129a5cca590aa73996a26642a531299e9
          - 2479691a5a91051d0b71552ecbcf6724a45409a7
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2000
      - run: cp test.sh /tmp/test.sh
      - run: git checkout ${{ matrix.revision }}
      - run: /tmp/test.sh
